### ISSUE TITLE
Failure to parse `FlawedGrace-ForDistribution.idb`

### ISSUE THREAD

**Issue by emesare** [Vector35/idb-rs#9]
[FlawedGrace-ForDistribution.idb.txt](https://github.com/user-attachments/files/17267409/FlawedGrace-ForDistribution.idb.txt)
```
thread 'test::parse_idbs' panicked at src/lib.rs:671:17:
til parsing `TILTypeInfo::tiinfo`

Caused by:
    Reserved Basic Type

Stack backtrace:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/backtrace.rs:331:13
   3: anyhow::error::<impl anyhow::Error>::msg
             at /Users/emesare/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.89/src/error.rs:85:36
   4: anyhow::__private::format_err
             at /Users/emesare/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.89/src/lib.rs:690:13
   5: idb_rs::til::TypeRaw::read
             at ./src/til.rs:170:43
   6: idb_rs::til::TILTypeInfo::read
             at ./src/til.rs:48:25
   7: idb_rs::til::section::TILSection::read_bucket_normal::{{closure}}
             at ./src/til/section.rs:353:22
   8: core::iter::adapters::map::map_try_fold::{{closure}}
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/iter/adapters/map.rs:96:28
   9: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/iter/traits/iterator.rs:2462:21
  10: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/iter/adapters/map.rs:122:9
  11: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/iter/adapters/mod.rs:201:9
  12: core::iter::traits::iterator::Iterator::try_for_each
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/iter/traits/iterator.rs:2524:9
  13: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/iter/adapters/mod.rs:184:14
  14: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/alloc/src/vec/spec_from_iter_nested.rs:26:32
  15: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/alloc/src/vec/spec_from_iter.rs:33:9
  16: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/alloc/src/vec/mod.rs:2836:9
  17: core::iter::traits::iterator::Iterator::collect
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/iter/traits/iterator.rs:2054:9
  18: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::{{closure}}
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/result.rs:1930:51
  19: core::iter::adapters::try_process
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/iter/adapters/mod.rs:170:17
  20: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/result.rs:1930:9
  21: core::iter::traits::iterator::Iterator::collect
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/iter/traits/iterator.rs:2054:9
  22: idb_rs::til::section::TILSection::read_bucket_normal
             at ./src/til/section.rs:352:25
  23: idb_rs::til::section::TILSection::read_bucket
             at ./src/til/section.rs:342:13
  24: idb_rs::til::section::TILSection::read_inner
             at ./src/til/section.rs:99:21
  25: idb_rs::til::section::TILSection::read
             at ./src/til/section.rs:86:17
  26: idb_rs::IDBParser<I>::read_til_section::{{closure}}
             at ./src/lib.rs:75:34
  27: idb_rs::read_section
             at ./src/lib.rs:129:18
  28: idb_rs::IDBParser<I>::read_til_section
             at ./src/lib.rs:71:9
  29: idb_rs::test::parse_idbs
             at ./src/lib.rs:666:33
  30: idb_rs::test::parse_idbs::{{closure}}
             at ./src/lib.rs:603:20
```

**Comment by rbran** [comment]
same issue that #8, but in 32bits.

**Comment by rbran** [comment]
Fixed on https://github.com/rbran/idb-rs/commit/5957e9e13be9fd73f2851b9b8b53e1aae2305123
